const Products = [
    {
        _id: '1',
        name: 'Water Lily Plant',
        category: 'Aquatic Plants',
        image: '/images/AquaticPlants/Waterlily2.jpeg',
        type: 'plant with pot',
        price: 1200,
        countInStock: 5,
        description: 'Low-maintenance, high-impact beauty for your garden',
      
    },
    {
        _id: '2',
        name: 'Golden Barrel Cactus',
        category: 'Cacti',
        image: '/images/Cacti/GoldenBarrelCactus.jpg',
        type: 'plant with pot',
        size: 'Small',
        price: 800,
        countInStock: 6,
        description: 'A low-maintenance, eye-catching addition to your home or garden',
    },
    {
        _id: '3',
        name: 'Prickly pear Cactus',
        category: 'Cacti',
        image: '/images/Cacti/PricklyPearCactus.jpg',
        type: 'plant with pot',
        size: 'Medium',
        price: 850,
        countInStock: 8,
        description: 'A unique and resilient plant with edible fruits and beautiful flowers',
    },
    {
        _id: '4',
        name: 'Yellow Rose',
        category: 'Flowers',
        image: '/images/Flowers/Rose2.jpg',
        type: 'plant',
        size: 'Small',
        price: 400,
        countInStock: 10,
        description: 'Add a touch of sunshine to your garden with this vibrant and fragrant flower',
    },
    {
        _id: '5',
        name: 'White Orchid',
        category: 'Flowers',
        image: '/images/Flowers/Orchid2.jpg',
        type: 'plant',
        size: 'Small',
        price: 500,
        countInStock: 10,
        description: 'Add a touch of elegance and sophistication to your home with this exotic and low-maintenance bloom',
    },
    {
        _id: '6',
        name: 'Mango (Budded)',
        category: 'Fruits',
        image: '/images/Fruits/Mango(Budded).png',
        type: 'plant',
        size: 'Small',
        price: 1100,
        countInStock: 25,
        description: 'Enjoy juicy, delicious mangoes at home with this easy-to-grow budded plant',
    },
    {
        _id: '7',
        name: 'Coriander',
        category: 'Herbs',
        image: '/images/Herbs/Coriander.jpg',
        type: 'seeds',
        price: 50,
        countInStock: 55,
        description: 'Add a burst of citrusy flavor to your dishes with this easy-to-grow herb',
    },
    {
        _id: '8',
        name: 'Snake Plant',
        category: 'Indoor Plants',
        image: '/images/IndoorPlants/SnakePlant.jpg',
        type: 'plant with pot',
        size: 'Medium',
        price: 600,
        countInStock: 20,
        description: 'The low-maintenance, air-purifying plant that is perfect for any home',
    },
    {
        _id: '9',
        name: 'Swiss cheese Plant',
        category: 'Indoor Plants',
        image: '/images/IndoorPlants/SwissCheesePlant.jpg',
        type: 'plant with pot',
        size: 'Medium',
        price: 600,
        countInStock: 25,
        description: 'Add a touch of unique beauty and air-purifying power to your home with this easy-care plant',
    },
    {
        _id: '10',
        name: 'Carrot',
        category: 'Vegetables',
        image: '/images/Vegetables/CarrotSeeds.jpg',
        type: 'seeds',
        price: 60,
        countInStock: 50,
        description: 'Grow your own delicious, crunchy carrots with these easy-to-plant seeds',
    },
    {
        _id: '11',
        name: 'Hand Shovel',
        category: 'Gardening Tools',
        image: '/images/GardeningTools/HandShovel.jpg',
        price: 450,
        type: 'tools',
        countInStock: 15,
        description: 'Ideal for any task, from digging holes to transplanting plants',
    },
  ]
  
  module.exports = Products;
  